import LoginPage from "../pages/LoginPage";
import ProductsPage from "../pages/ProductsPage";
import CheckoutPage from "../pages/CheckoutPage";
describe('Test add to cart functionality', () => {
    const loginPage = new LoginPage();
    const productsPage = new ProductsPage();
    const checkoutPage = new CheckoutPage();
    beforeEach(() => {
        cy.viewport(1920, 1080);
        loginPage.userLogin("standard_user", "secret_sauce");
    });
    it('Add products to the Cart', () => {
        productsPage.productDashboard();
        cy.wait(500);
        productsPage.viewProductDetails();
        cy.wait(500);
        productsPage.addingToCart();
        cy.wait(500);
        productsPage.viewCartItem();
        cy.wait(500);
        productsPage.goingToCheckoutPage();
        cy.wait(500);
    });
    it("Verify the product is purchase successfully", () => {
        productsPage.productDashboard();
        cy.wait(500);
        productsPage.viewProductDetails();
        cy.wait(500);
        productsPage.addingToCart();
        cy.wait(500);
        productsPage.viewCartItem();
        cy.wait(500);
        productsPage.goingToCheckoutPage();
        cy.wait(500);
        checkoutPage.addUserInfo("Hasan", "Shovon", "1216");
        cy.wait(500);
        checkoutPage.finishPurchase();
        cy.wait(500);
        checkoutPage.purchaseCompleteAssertion("Thank you for your order!");
        cy.wait(500);
      });
      it("Back to home from successful page", () => {
        productsPage.productDashboard();
        cy.wait(500);
        productsPage.viewProductDetails();
        cy.wait(500);
        productsPage.addingToCart();
        cy.wait(500);
        productsPage.viewCartItem();
        cy.wait(500);
        productsPage.goingToCheckoutPage();
        cy.wait(500);
        checkoutPage.addUserInfo("Hasan", "Shovon", "1216");
        cy.wait(500);
        checkoutPage.finishPurchase();
        cy.wait(500);
        checkoutPage.purchaseCompleteAssertion("Thank you for your order!");
        cy.wait(500);
        checkoutPage.backToHomePage();
        cy.wait(500);
        productsPage.productDashboard();
      });
      it("Verify the purchase cancel from overview page", () => {
        productsPage.productDashboard();
        cy.wait(500);
        productsPage.viewProductDetails();
        cy.wait(500);
        productsPage.addingToCart();
        cy.wait(500);
        productsPage.viewCartItem();
        cy.wait(500);
        productsPage.goingToCheckoutPage();
        cy.wait(500);
        checkoutPage.addUserInfo("Hasan", "Shovon", "1216");
        cy.wait(500);
        checkoutPage.cancelFromOverviewPage();
        cy.wait(500);
      });
      it("verify product purchase is cancelled", () => {
        productsPage.productDashboard();
        cy.wait(500);
        productsPage.viewProductDetails();
        cy.wait(500);
        productsPage.addingToCart();
        cy.wait(500);
        productsPage.viewCartItem();
        cy.wait(500);
        productsPage.goingToCheckoutPage();
        cy.wait(500);
        checkoutPage.addUserInfo("Hasan", "Shovon", "1216");
        cy.wait(500);
        checkoutPage.cancelPurchase();
        productsPage.productDashboard();
     });
});